name: Fitbit Token Refresh & Data Update

# ⚠️ 排程已停用：本機 crontab 是 Fitbit token 的唯一 refresh 來源
# Fitbit refresh token 是一次性的，兩邊同時刷會互相踩
# 保留 workflow_dispatch 作為緊急手動備援

on:
  # schedule 已移除 — 避免與本機 crontab 搶 refresh token
  workflow_dispatch:  # 手動觸發（緊急備援用）

permissions:
  contents: write

jobs:
  refresh-fitbit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Refresh token & fetch data
        env:
          FITBIT_ENCRYPT_KEY: ${{ secrets.FITBIT_ENCRYPT_KEY }}
        run: python3 scripts/fitbit_cloud_refresh.py

      - name: Commit & push
        id: commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/fitbit.json scripts/.fitbit_token.enc
          if git diff --cached --quiet; then
            echo "No changes to commit"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            git commit -m "auto: fitbit data + token refresh [skip-translate]"
            git push
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Trigger deploy
        if: steps.commit.outputs.changed == 'true'
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/zarqarwi/paulkuo.tw/actions/workflows/deploy.yml/dispatches \
            -d '{"ref":"main"}'
